In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [4]:
vector=tf.constant([10,10])
print(vector)
print(vector.ndim)

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [5]:
matrix=tf.constant([[10,7],[7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [6]:
basic_tensor=tf.constant([[10,11],[12,13]])
print(basic_tensor)

tf.Tensor(
[[10 11]
 [12 13]], shape=(2, 2), dtype=int32)


In [7]:
print(basic_tensor+10)
print(basic_tensor-10)
print(basic_tensor*10)
print(basic_tensor/10)

tf.Tensor(
[[20 21]
 [22 23]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100 110]
 [120 130]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1.  1.1]
 [1.2 1.3]], shape=(2, 2), dtype=float64)


In [10]:
tensor_011=tf.constant([[2,2],[4,4]])
tensor_012=tf.constant([[2,3],[4,5]])
print(tf.matmul(tensor_011,tensor_012))


tf.Tensor(
[[12 16]
 [24 32]], shape=(2, 2), dtype=int32)
